# Hexo 基本設定
title: Melody K Blog
subtitle: 用資料與內容，打造個人品牌
description: 國內外旅遊｜青年國際交流｜大學生實習心得
author: Melody Kao
language: zh-TW
timezone: ''

# 網站 URL（記得用你的 GitHub Pages 網址）
url: https://melodykao000.github.io
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: true
  trailing_html: true

# 文章設定
post_asset_folder: true
new_post_name: :title.md
default_layout: post

# 分類 / 標籤
default_category: uncategorized

# 分頁
per_page: 10
pagination_dir: page

# 插件設定
sitemap:
  path: sitemap.xml
feed:
  type: atom
  path: atom.xml
  limit: 20

# 主題
theme: icarus

# 部署設定
deploy:
  type: git
  repo: https://github.com/melodykao000/melodykao000.github.io.git
  branch: main
