version: 6.1.1

navbar:
  menu:
    Home: /
    Archives: /archives/
    Categories: /categories/
    Tags: /tags/
    Services: /services/
    About: /about/
    Contact: /contact/
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/melodykao000

banner:
  image: /images/cover.jpg
  title: 用資料與內容，打造個人品牌
  subtitle: 國內旅遊・國外旅遊・青年國際交流・實習分享

widgets:
  - type: profile
    position: left
    author: Melody Kao
    author_title: Content × Data Learner
    location: Taiwan
    avatar: /images/avatar.jpg
    social_links:
      github: https://github.com/melodykao000
      instagram: https://instagram.com/你的IG
      email: mailto:onpu92@gmail.com

  - type: recent_posts
    position: right
    count: 5
  - type: categories
    position: right
  - type: tags
    position: right
  - type: toc
    position: right

article:
  thumbnail: true
  readmore: true
  toc: true
  excerpt_length: 140

search:
  type: insight

stylesheets:
  - /css/custom.css
