version: 6.1.1

navbar:
  menu:
    服務:
      children:
        演講與工作坊:
          url: /services/speaking/
        自媒體合作:
          url: /services/brand-partnership/
        1:1 諮詢:
          url: /services/consulting/

    作品與案例:
      children:
        講座花絮與回饋:
          url: /cases/speaking/
        品牌合作案例:
          url: /cases/brand/

    部落格:
      children:
        青年機會與補助:
          url: /blog/youth-opportunities/
        實習與職涯:
          url: /blog/internship-career/
        美食與旅遊:
          url: /blog/lifestyle/

    關於我:
      url: /about/
    訂閱電子報:
      url: /subscribe/



links:
  instagram:
    icon: fab fa-instagram
    url: https://www.instagram.com/__kpc._/

banner:
  image: /images/cover.jpg
  title: 用資料與內容，打造個人品牌
  subtitle: 國內旅遊・國外旅遊・青年國際交流・實習分享

widgets:
  - type: profile
    position: left
    author: 高杯
    author_title: 海外實習 x 青年資源分享
    location: Taiwan
    avatar: /images/avatar.jpg
    social_links:
      instagram: https://www.instagram.com/__kpc._/

  - type: recent_posts
    position: right
    count: 5
  - type: categories
    position: right
  - type: tags
    position: right
  - type: toc
    position: right

article:
  thumbnail: true
  readmore: true
  toc: true
  excerpt_length: 140

search:
  type: insight

stylesheets:
  - /css/custom.css
